const express = require('express');
const app = express();
const bodyparser = require('body-parser');


app.use(bodyparser.urlencoded({extended:false}));
app.use(bodyparser.json());

const DB = {
    Noticia:[
        {
            title: 'Livro aborda a matéria orgânica do solo em ambientes tropicais e subtropicais, pioneiro no mundo',
            dataNoticia: '19/04/23',
            textoNoticia: [
                'A Embrapa Meio Ambiente acaba de lançar o livro “Entendendo a matéria orgânica do solo em ambientes tropical e subtropical”, primeiro no mundo que busca sistematizar informações sobre estudos realizados há mais de cinco décadas nestes ambientes. As informações contidas no livro poderão colaborar com a agricultura brasileira, além de outros países com climas tropical e subtropical. ',
                'Os editores do livro, Wagner Bettiol e Cristiano Andrade da Embrapa Meio Ambiente, Ladislau Martin-Neto da Embrapa Instrumentação, Carlos Silva da Universidade Federal de Lavras e Carlos Cerri da Escola Superior de Agricultura “Luiz de Queiroz”, uniram os principais especialistas do Brasil para elaborar esta obra, que na realidade é um tratado sobre matéria orgânica do solo nestes ambientes. São 788 páginas de informações divididas em 27 capítulos e inteiramente grátis para a comunidade.',
                'De acordo com Bettiol, o desafio de aumentar a quantidade de matéria orgânica nas camadas superficiais do solo em ambientes tropical e subtropical pode ser vencido em grande parte das áreas agrícolas, mas é preciso identificar práticas de manejo que permitam alocar mais carbono no sistema e reduzir as perdas. Ele comenta que desde a adoção do plantio direto a partir da década de 1970, na região sul do Brasil, com a preservação do recurso solo pela redução da erosão e o uso de rotação de culturas, percebeu-se, de forma mais clara, a importância de se preservar ou aumentar a matéria orgânica do solo, o que é discutido amplamente nessa publicação.',
                'No livro também são encontrados exemplos de como novas tecnologias podem ser geradas a partir da base conceitual que há disponível no Brasil e em outros países, comenta Cristiano Andrade. De acordo com ele, os autores discutem amplamente sobre a matéria orgânica do solo, demonstrando a sua importância para aumentar a produtividade agrícola, para melhorar a qualidade dos solos, para sequestrar carbono e como uma ferramenta para mitigar os efeitos das mudanças climáticas. ',
                'Os autores geraram e compilaram informações das últimas décadas a fim de demonstrar a importância da conservação da biodiversidade para aumentar a produção agrícola de forma sustentável e para mitigar as emissões de gases de efeito estufa nos ambientes tropical e subtropical. \n' +
                  'No tocante à agricultura, explica Bettiol, “é fundamental o avanço e correção de rumos na mitigação e adaptação às mudanças climáticas  escassez hídrica, distribuição irregular das chuvas e alteração do ciclo de pragas e doenças entre outras, no uso racional e eficiente dos recursos minerais, na viabilização de fontes alternativas de nutrientes, na redução da dependência internacional de insumos, como os fertilizantes e pesticidas, na prevenção da degradação dos solos, na redução de uso de pesticidas  químicos pelo adequado manejo do ambiente produtivo e na ampliação do uso dos bioinsumos. Praticamente, todos esses aspectos têm relação com a matéria orgânica do solo, foco deste livro”. ',
                'Todas essas práticas de manejo e sistemas de produção para uma agricultura de baixa emissão de carbono estão representadas no livro, como os modernos sistemas de integração lavoura-pecuária e lavoura-pecuária-floresta, que incorporam as premissas do plantio direto, que crescem no país para a produção integrada de grãos, carne, leite e madeira, viabilizando a recuperação de áreas extensas de pastagens degradadas.\n' +
                  'Também são discutidos em capítulos os resíduos orgânicos gerados a partir da exportação pelas colheitas para as agroindústrias ou para o meio urbano que podem e devem ser retornados ao solo agrícola, como fonte de nutrientes e matéria orgânica. No Brasil, temos casos de sucesso na reciclagem de resíduos, como o do setor de açúcar e etanol, nos quais todos os resíduos gerados são utilizados diretamente no próprio sistema de produção, além da geração de energia, o que está alinhado com conceitos de governança ambiental, social e corporativa - ESG (environmental, social and governance) e economia circular, muito embora essa evolução conceitual, normativa e tecnológica no setor ocorra desde a década de 60, comenta Cristiano Andrade. ',
                'Os engenheiros agrônomos Walter Silva e Alfredo Tsuzuki, ambos da Associação Brasileira de Insumos para Agricultura Sustentável, comentam que o livro supri uma necessidade dos diferentes atores que atuam no mercado de matéria orgânica, como as empresas de fertilizantes orgânicos e organominerais, condicionadores de solo e substratos.',
                'A publicação atende a cinco objetivos de desenvolvimento sustentável, da ONU, especificamente o ODS 2 - Fome zero e agricultura sustentável, ODS 7 - Energia acessível e limpa, ODS 12 - Consumo e produção sustentável, ODS 13 - Ação contra a mudança global do clima e o ODS 15 - Vida terrestre. O livro pode ser acessado aqui.\n' +
                  '\n'
              ],
              autorNoticia: 'Cristina Tordin '
        },
        {
            title: 'Seminário CanaMS reúne técnicos de usinas dos estados de MS, PR, SP e MG',
            dataNoticia: '19/04/23',
            textoNoticia: [
              'Embrapa Agropecuária Oeste foi uma das empresas que apresentaram resultados de pesquisa, que tratou sobre a manutenção e a retirada do palhiço no canavial',
              ' ',
              'Um público presencial de quase 200 participantes, vindos de São Paulo, Paraná, Minas Gerais e Mato Grosso do Sul, e mais de 500 participantes na transmissão ao vivo do 1° Seminário CanaMS de 2023, 8º edição do evento, realizado no dia 14 de abril, no auditório da Embrapa Agropecuária Oeste. O evento foi gravado e é possível assistí-lo pelo Canal da Embrapa no Youtube: https://bit.ly/3MmAiok. Os participantes assistiram a palestras sobre previsão do tempo para a safra 2023/2024 para a cultura da cana-de-açúcar, recolhimento do palhiço, manejo de nitrogênio, transporte e qualidade da matéria-prima, fertilizantes e bioinsumos.',  
              'Além disso, o público virtual pôde acompanhar entrevistas feitas durante os intervalos no podcast Agro Ciência, comandado pelo professor Fábio Mascarenhas, da UFGD, em parceria com a Embrapa Agropecuária Oeste, com a participação do pesquisador Cesar José da Silva e do gestor da TCH Gestão Agrícola José Trevelin Jr. O Seminário foi uma realização da Embrapa Agropecuária Oeste e TCH Gestão Agrícola, com apoio da Biosul e Sulcanas. Teve o patrocínio das seguintes empresas: Biotrop, Euroforte, Hinove, Kracht, Koppert, Solubio, Sumitomo Chemical, Ubyfol e Union Agro.',
              '“Este sempre foi um evento técnico, com os temas de palestras sugeridas pelo setor sucroenergético, que tem como um dos focos a sustentabilidade. Além dos resultados de pesquisa para a cultura da cana-de-açúcar, vemos também que este é um momento de fazer intercâmbio de conhecimentos entre os participantes, de aprender um com os outros, e também podermos pontuar pautas para novos trabalhos”, disse o chefe-geral da Embrapa Agropecuária Oeste, Harley Nonato de Oliveira.', 
              'Ele enfatizou que o seminário é um evento que se preocupa com as causas sociais e “mostra que o setor é diferenciado”. Isso porque os apoiadores e patrocinadores incluíram na programação uma apresentação do Hospital do Amor, de Barretos, SP, por Rubiquinho de Carvalho, convidado especial da Euroforte. O hospital existe em outras localidades do Brasil e está em construção em Dourados, MS. “Tem caráter de sensibilidade fundamental”, afirmou Oliveira, agradecendo pelas parcerias.',
              'José Trevelin Jr., gestor da TCH Gestão Agrícola, lembrou que devido às demandas do setor sucroenergético de Mato Grosso do Sul foi criado o Seminário CanaMS há oito anos, iniciado pela Embrapa Agropecuária Oeste, Biosul e TCH Gestão Agrícola. “Cases de sucesso de Mato Grosso do Sul, tecnologias vindas de fora, assuntos desenvolvidos pela própria Embrapa, esse evento é um momento de interação gigante desde 2016”, pontuou Trevelin.',
              'Previsão do tempo',
              'A primeira palestra do Seminário normalmente é sobre a previsão do tempo para a safra seguinte de cana-de-açúcar. O agrometeorologista e engenheiro agrônomo da Rural Clima, Marcos Antônio dos Santos, respondeu às perguntas que não queriam se calar: “O El Niño vai chegar ou não? Vem geada para Mato Grosso do Sul?”. Segundo ele, a resposta para a primeira pergunta é de que “nos próximos 24 meses, há possibilidade de formação de El Niño [quando as águas do Oceano Pacífico aumentam de temperatura e traz chuva]. Ainda não é possível saber a intensidade. Acredita-se que apareça mais para o final, mas não é certo”, iniciou a resposta.',
              'Segundo ele, a maioria das pessoas baseiam suas tomadas de decisão no campo somente pela presença ou não dos fenômenos El Niño e a La Niña, porém, Santos enfatizou que diversos fatores de clima devem ser analisados. “E La Niña e El Niño não são algo que acontecem de forma instantânea. Ainda estamos na neutralidade”.',
              'O agrometeorologista informou que, historicamente, os fenômenos acontecem da seguinte forma: três anos seguidos de La Niña são sucedidos por um ano de El Niño. No cenário atual, o oceano Pacífico está se aquecendo em processo rápido. A região 2 está quente e chuvas mais regulares no Chile, entrada de frentes frias para a região mais sul do Brasil. “A quantidade de chuva ao longo dos próximos 15 dias de abril para MS é alta. Para o setor da cana, está complicando o início da safra. Favorece o desenvolvimento e o plantio, mas atrapalha a colheita. A ATR não está querendo subir”, constatou Santos.',
              'Segundo o agrometeorologista, vai haver algumas pancadas de chuvas por mês, o que pode atrapalhar muito o dia a dia da usina, como a moagem e o estoque. “Mas já sabendo de antemão, dá para se planejar melhor”, alerta.',
              '“E a geada? A Rural Clima só liberta alerta de geada com sete dias de antecedência. Antes, é proibido. Pode até falar que tem massa de ar polar, mas existem vários fatores que podem contribuir ou mitigar os efeitos de uma geada. Massa de ar polar é o grande combustível para geada, porém, também são necessários umidade, vento, nebulosidade que pode contribuir ou mitigar os efeitos da geada. As grandes geadas se dão com céu aberto”, afirmou Santos. Outro fator levantado por ele é a parte nutricional da planta.',
              'Mesmo assim, ele falou de um dos períodos mais críticos para geada no Brasil: do dia 20 de maio até 10 de junho. “Não estou falando que vai gear, mas é preciso ter ‘olhos de lince’ nesse período. Uma massa de ar polar deve avançar um pouco mais no Brasil. É para ficar de olho para tomar algumas ações”, alertou.', 
              'Adubação potássica e palhiço',
              'O pesquisador da Embrapa Agropecuária Oeste, Carlos Hissao Kurihara, apresentou resultados de projeto realizados em parceria com a Adecoagro, na Usina Angélica, em Angélica, MS. Este trabalho foi executado em parceria entre os pesquisadores Kurihara, Luís Staut e Cesar José da Silva.',
              'Potássio - O potássio é um elemento que é extraído em grande quantidade pela cana. O mineral regula a abertura e fechamento dos estômatos, transpiração (aumenta a eficiência) e resulta em melhoria no transporte de sacarose pela planta. Também confere resistência a geadas, seca, doenças, acamamento e contribui com a melhoria da produção industrial da cana.',
              'Já o excesso de absorção pode causar desbalanço nutricional, induzindo à deficiência de cálcio e magnésio, ao atraso na concentração de sacarose e ao aumento dos teores de cinza no açúcar.',
              'Palhiço - O palhiço pode contribuir para a manutenção da umidade do solo. Com a camada de palhada, há redução de impacto das chuvas no solo, menor escorrimento de água no solo e menor perda de água e solo por erosão. Contribui para a redução de planta daninha no sistema. Como contém nutrientes, devido à decomposição do resíduo vegetal, pode contribuir para a reciclagem de nutrientes (principalmente K, Mg e Ca), sobretudo nos ponteiros.',
              'O palhiço tem poder calorífico alto e maior que o bagaço. Há interesse na cogeração de energia desse material, desde que o preço seja menor que o custo. “A demanda pela cogeração de energia também será aumentada à medida em que se viabiliza a tecnologia de produção de etanol a partir de celulose (etanol de segunda geração)”, acrescenta Kurihara.',
              'Experimento - Os pesquisadores conduziram um experimento em parceria com a Adecoagro para avaliar o efeito da adubação potássica em ambiente restritivo, em condições de ausência ou presença de recolhimento de palhiço. Foi instalado em área de reforma no distrito de Ipezal, em Angélica, MS. Realizaram dois tipos de manejo de palhiço (com recolhimento e sem recolhimento), cinco doses de potássio (0, 75, 150, 225 e 300 kg/ha de KO) e quatro blocos. A conclusão é que o recolhimento do palhiço influenciou a disponibilidade de potássio no solo e tendeu a diminuir a altura de plantas, o diâmetro de colmos e a produtividade da cana; já a manutenção do palhiço propiciou máxima produtividade de colmo com menor dose de potássio; em ambiente restritivo, de baixa fertilidade, a indicação de adubação potássica, comumente adotada, de aplicar quantidade de K2O equivalente a 1,3 vezes a produtividade esperada (1,3 x TCH) não permite a obtenção do pleno potencial produtivo da cana.',
              'Outros temas',
              'Foram apresentados também resultados de pesquisa da Euroforte sobre a evolução do nitrogênio na cana-soca, palestra ministrada por João Pedro Alves dos Santos e Flávio Pompei; da Usina Eldorados – Atvos, sobre o equilíbrio entre rendimento operacional e qualidade da matéria-prima no corte, transbordo e transporte (CTT), pelo palestrante da empresa Renato Modesto de Oliveira; da Hinove, com William Trevisan, sobre fertilizantes especiais para a cana-soca; do Centro Universitário Moura Lacerda, foi explanado pelo professor Alexandre de Sene Pinto, o tema sobre uso inovador de bioinsumos nos canaviais.',
              ' '
            ],
            autorNoticia: 'Sílvia Zoche Borges ' 
        }
    ]
};

app.get("/noticias", async(req, res)=>{
    res.status = 200;
    res.json(DB)
});

app.set('porta', process.env.PORT || 3000)

app.listen(app.get('porta'), () =>{
    console.log("Servidor rodando na porta ", app.get('porta'));
})